export const OTHER_INFO = {
  brand: "Thương hiệu",
  guarantee: "Bảo hành",
  cpu: "CPU",
  series: "Series",
  socket: "Socket",
  totalCores: "Số nhân xử lý",
  totalThreads: "Số luồng xử lý",
  codeName: "Code name",
  generation: "Thế hệ",
  turboFrequency: "Tốc độ xử lý",
  cache: "Cache",
  processorGraphics: "Chip đồ họa",
  tdp: "TDP",
  memoryTypes: "Bộ nhớ hỗ trợ",
  producerchip: "Nhà sản xuất chipset",
  name: "Tên",
  gpu: "GPU",
  memory: "Bộ nhớ",
  gpulock: "GPU clock",
  pci: "Giao tiếp PCI",
  cudacore: "Số lượng đơn vị xử lý",
  connector: "Cổng kết nối",
  fan: "Tản nhiệt",
  power: "Nguồn đề xuất",
  size: "Kích thước",
};
