export const OTHER_INFO = {
  brand: "Thương hiệu",
  guarantee: "Bảo hành",
  cpu: "CPU",
  series: "Series",
  socket: "Socket",
  totalCores: "Số nhân xử lý",
  totalThreads: "Số luồng xử lý",
  codeName: "Code name",
  generation: "Thế hệ",
  turboFrequency: "Tốc độ xử lý",
  cache: "Cache",
  processorGraphics: "Chip đồ họa",
  tdp: "TDP",
  memoryTypes: "Bộ nhớ hỗ trợ",
  producerchip: "Nhà sản xuất chipset",
  name: "Tên",
  gpu: "GPU",
  memory: "Bộ nhớ",
  gpulock: "GPU clock",
  pci: "Giao tiếp PCI",
  cudacore: "Số lượng đơn vị xử lý",
  connector: "Cổng kết nối",
  fan: "Tản nhiệt",
  power: "Nguồn đề xuất",
  size: "Kích thước",
  chipset: "Chipset",
  totalRam: "khe ram tối đa",
  styleRam: "kiểu ram hỗ trợ",
  maxmemory: "Hỗ trợ bộ nhớ tối đa",
  storege: "Lưu trữ",
  m2: "Kiểu khe M.2 hỗ trợ",
  multiGPU: "Multi-GPU",
  led: "Đèn LED",
  totalusb: "Số cổng USB",
  LAN: "LAN",
  partNumber: "Part-number",
  color: "Màu sắc",
  storegeMemory: "Dung lượng",
  bus: "Bus",
  serieschip: "Series chip đồ họa",
  styleHardDrive: "Kiểu ổ cứng",
  NAND: "Bộ nhớ NAND",
  reading: "Tốc độ đọc",
  write: "Tốc độ ghi",
  maxpower: "Công suất tối đa",
  efficiency: "Hiệu suất",
  cable: "cáp rời",
  totalConnector: "Số cổng cắm",
  powerInput: "Nguồn đầu vào",
  need: "Nhu cầu",
  material: "Chất liệu",
  materiallib: "Chất liệu nắp hông",
  heatsinkType: "Dạng tản nhiệt",
  sizefan: "kích thước quạt",
  socketSup: "Socket được hỗ trợ",
  sizeRadiator: "Kích thước Radiator (cm)",
  rotationPump: "Số vòng quay của bơm (RPM)",
  rotationFan: "Số vòng quay của quạt (RPM)",
  CFM: "Lưu lượng không khí (CFM)",
  height: "Chiều cao",
  resolution: "Độ phân giải",
  displayResolution: "Tần số quét",
  responsetime: "Thời gian phản hồi",
  luminosity: "Độ sáng",
  HDR: "HDR",
  connectorKeyboard: "Kết nối bàn phím",
  typeSwitch: "Kiểu switch",
  keyFun: "Phím chức năng",
  connectortype: "Kiểu kết nối",
  sensor: "Dạng cảm biến",
  type: "Kiểu",
  speed: "Tốc độ vòng quay",
};
