export const BUILD_ACTION = {
  ADD_ITEM_PRODUCT: "BUILD/ADD_ITEM_PRODUCT",
  UPDATE_ITEM_PRODUCT: "BUILD/UPDATE_ITEM_PRODUCT",
  DELETE_ITEM_PRODUCT: "BUILD/DELETE_ITEM_PRODUCT",
  DELETE_LIST_PRODUCT: "BUILD/DELETE_LIST_PRODUCT",
};
